version: "3"
services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    image: mojzu/web:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "1234:1234"
    volumes:
      - ./:/git
    working_dir: /git
